### DISCUSSION TITLE
friends/index.html

### DISCUSSION THREAD

**Discussion by giscus** [SouthFox-D/SouthFox-D.github.io#57] [博客评论]
# friends/index.html

友链页面

https://blog.southfox.me/friends/

**Comment by lingyf** [comment]
大佬，申请个友链，嘻嘻 (●'◡'●)
```yml
Name: Albert's Blog
Desc: 逆水行舟 不进则退
Link: https://blog.lingyf.com
Icon: https://blog.lingyf.com/images/icon.svg
```
