### ISSUE TITLE
关于样式

### ISSUE THREAD

**Issue by kunl** [SouthFox-D/SouthFox-D.github.io#79]
如果是 side_meta 需要固定悬浮的话
 ```css 
#side_meta {
    position: sticky;
    top: 80px;
}
```
就行了；
另外这个蓝色背景，太晃眼了😂
